language: python
sudo: enabled
services:
    - mysql
python:
    - "3.5"
env:
    global:
    - TRAVIS=true
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS wechat_ticket;'
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install pymysql
    
script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test
